{
  "comments": [
    {
      "key": {
        "uuid": "1a76adc5_f0db34eb",
        "filename": "core/vnf_controller.py",
        "patchSetId": 1
      },
      "lineNbr": 56,
      "author": {
        "id": 1306
      },
      "writtenOn": "2016-09-05T09:13:58Z",
      "side": 1,
      "message": "This was solution of original multi VM patch. While processing review comments, I\u0027ve missed, that it is essential. Thus I\u0027ve added a comment to avoid similar issues in the future.",
      "revId": "4ba781b2b5e1547d6d06e4526f7e12ecddd35dfb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}